### ISSUE TITLE
android-5.1 branch

### ISSUE THREAD

**Issue by pix106** [omnirom/android_system_core_old#4]
Hi,
android-5.1 branch was deleted recently, projects depending on it, such as minimal TWRP tree, fail to repo sync.
Is there an archive repository, or a replacement ?
Thanks

**Comment by rafspiny** [comment]
Pushing this up. Is it possible to reintroduce the branch?
Temporarily, I used commit fbe25477fc8587827b41ab525a5e955a57519f4e in the manifest.xml file.
